<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'] . '/Thrift.php';

$GLOBALS['xl_relation_E_FollowUserType'] = array('ALL'=>2, 'USER'=>0, 'SHOP'=>1);

final class xl_relation_FollowUserType {
    const ALL = 2;
    const USER = 0;
    const SHOP = 1;
    public static $__names = array(2=>'ALL', 0=>'USER', 1=>'SHOP');
}

$GLOBALS['xl_relation_E_RelationType'] = array('Follow'=>1, 'Followed'=>2);

final class xl_relation_RelationType {
    const Follow = 1;
    const Followed = 2;
    public static $__names = array(1=>'Follow', 2=>'Followed');
}

?>
