<?php
 return array (
  'sh' => 
  array (
    'index' => 
    array (
      'pos_id' => '15',
      'pos_pid' => '0',
      'pos_name' => '首页',
      'identifier' => 'index',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '1',
      'created' => '0',
      'updated' => '1445933970',
      'city' => 'sh',
      'child' => 
      array (
        'index_latest_event' => 
        array (
          'pos_id' => '24',
          'pos_pid' => '15',
          'pos_name' => '最新活动',
          'identifier' => 'index_latest_event',
          'pos_url' => '',
          'width' => '220',
          'height' => '125',
          'sequence' => '1',
          'created' => '1386146478',
          'updated' => '1454551636',
          'city' => 'sh',
        ),
        'index_img_large' => 
        array (
          'pos_id' => '19',
          'pos_pid' => '15',
          'pos_name' => '轮播大图',
          'identifier' => 'index_img_large',
          'pos_url' => '',
          'width' => '1200',
          'height' => '300',
          'sequence' => '2',
          'created' => '0',
          'updated' => '1398143521',
          'city' => 'sh',
        ),
        'index_img_small' => 
        array (
          'pos_id' => '17',
          'pos_pid' => '15',
          'pos_name' => '轮播小图',
          'identifier' => 'index_img_small',
          'pos_url' => '',
          'width' => '90',
          'height' => '60',
          'sequence' => '3',
          'created' => '0',
          'updated' => '1386652577',
          'city' => 'sh',
        ),
        'index_top_shop' => 
        array (
          'pos_id' => '16',
          'pos_pid' => '15',
          'pos_name' => '热门店铺',
          'identifier' => 'index_top_shop',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '4',
          'created' => '0',
          'updated' => '1386652626',
          'city' => 'sh',
        ),
        'index_value_pick' => 
        array (
          'pos_id' => '18',
          'pos_pid' => '15',
          'pos_name' => '超值精选',
          'identifier' => 'index_value_pick',
          'pos_url' => '',
          'width' => '220',
          'height' => '300',
          'sequence' => '5',
          'created' => '0',
          'updated' => '1386652745',
          'city' => 'sh',
        ),
        'index_brand' => 
        array (
          'pos_id' => '131',
          'pos_pid' => '15',
          'pos_name' => '首页品牌大图',
          'identifier' => 'index_brand',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1417404442',
          'updated' => '0',
          'city' => 'sh',
        ),
        'index_brand_logo' => 
        array (
          'pos_id' => '132',
          'pos_pid' => '15',
          'pos_name' => '首页品牌LOGO',
          'identifier' => 'index_brand_logo',
          'pos_url' => '',
          'width' => '110',
          'height' => '73',
          'sequence' => '99',
          'created' => '1417404487',
          'updated' => '0',
          'city' => 'sh',
        ),
        'index_market' => 
        array (
          'pos_id' => '133',
          'pos_pid' => '15',
          'pos_name' => '首页商场大图',
          'identifier' => 'index_market',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1417404520',
          'updated' => '0',
          'city' => 'sh',
        ),
        'index_market_logo' => 
        array (
          'pos_id' => '134',
          'pos_pid' => '15',
          'pos_name' => '首页商场LOGO',
          'identifier' => 'index_market_logo',
          'pos_url' => '',
          'width' => '110',
          'height' => '73',
          'sequence' => '99',
          'created' => '1417404544',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'iphone' => 
    array (
      'pos_id' => '13',
      'pos_pid' => '0',
      'pos_name' => '手机端',
      'identifier' => 'iphone',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '2',
      'created' => '0',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'phone_head' => 
        array (
          'pos_id' => '14',
          'pos_pid' => '13',
          'pos_name' => '头部推荐',
          'identifier' => 'phone_head',
          'pos_url' => '',
          'width' => '320',
          'height' => '142',
          'sequence' => '99',
          'created' => '0',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'nav' => 
    array (
      'pos_id' => '32',
      'pos_pid' => '0',
      'pos_name' => '导航',
      'identifier' => 'nav',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1386576656',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'nav_good_sort' => 
        array (
          'pos_id' => '33',
          'pos_pid' => '32',
          'pos_name' => '按分类',
          'identifier' => 'nav_good_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '1',
          'created' => '1386576691',
          'updated' => '1386638637',
          'city' => 'sh',
        ),
        'nav_brand_sort' => 
        array (
          'pos_id' => '34',
          'pos_pid' => '32',
          'pos_name' => '按品牌',
          'identifier' => 'nav_brand_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '2',
          'created' => '1386576719',
          'updated' => '1386638667',
          'city' => 'sh',
        ),
        'nav_region_sort' => 
        array (
          'pos_id' => '80',
          'pos_pid' => '32',
          'pos_name' => '按区域',
          'identifier' => 'nav_region_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '3',
          'created' => '1414553142',
          'updated' => '0',
          'city' => 'sh',
        ),
        'nav_circle_sort' => 
        array (
          'pos_id' => '35',
          'pos_pid' => '32',
          'pos_name' => '按商圈',
          'identifier' => 'nav_circle_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '4',
          'created' => '1386576742',
          'updated' => '1386638679',
          'city' => 'sh',
        ),
      ),
    ),
    'recommend_goods' => 
    array (
      'pos_id' => '36',
      'pos_pid' => '0',
      'pos_name' => '分类商品推荐',
      'identifier' => 'recommend_goods',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1386652994',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'recommend_goods_wome' => 
        array (
          'pos_id' => '38',
          'pos_pid' => '36',
          'pos_name' => '女装',
          'identifier' => 'recommend_goods_wome',
          'pos_url' => 'http://buy.mplife.com/good/list/gid/4',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1386653122',
          'updated' => '1386654875',
          'city' => 'sh',
        ),
        'recommend_goods_shoe' => 
        array (
          'pos_id' => '39',
          'pos_pid' => '36',
          'pos_name' => '鞋包.配饰',
          'identifier' => 'recommend_goods_shoe',
          'pos_url' => '',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1386653175',
          'updated' => '1386653310',
          'city' => 'sh',
        ),
        'recommend_goods_beautif' => 
        array (
          'pos_id' => '40',
          'pos_pid' => '36',
          'pos_name' => '美颜.家居',
          'identifier' => 'recommend_goods_beautif',
          'pos_url' => '',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1386653201',
          'updated' => '1414553291',
          'city' => 'sh',
        ),
      ),
    ),
    'recommend_brands' => 
    array (
      'pos_id' => '37',
      'pos_pid' => '0',
      'pos_name' => '分类品牌推荐',
      'identifier' => 'recommend_brands',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1386653036',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'recommend_brands_wom' => 
        array (
          'pos_id' => '42',
          'pos_pid' => '37',
          'pos_name' => '品牌.女装',
          'identifier' => 'recommend_brands_wom',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653671',
          'updated' => '0',
          'city' => 'sh',
        ),
        'recommend_brands_shoes' => 
        array (
          'pos_id' => '43',
          'pos_pid' => '37',
          'pos_name' => '品牌.女鞋',
          'identifier' => 'recommend_brands_shoes',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653730',
          'updated' => '1386654019',
          'city' => 'sh',
        ),
        'recommend_brands_underwear' => 
        array (
          'pos_id' => '44',
          'pos_pid' => '37',
          'pos_name' => '品牌.内衣',
          'identifier' => 'recommend_brands_underwear',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653789',
          'updated' => '1386654030',
          'city' => 'sh',
        ),
        'recommend_brands_men' => 
        array (
          'pos_id' => '45',
          'pos_pid' => '37',
          'pos_name' => '品牌.男装',
          'identifier' => 'recommend_brands_men',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653832',
          'updated' => '0',
          'city' => 'sh',
        ),
        'recommend_brands_accessories' => 
        array (
          'pos_id' => '46',
          'pos_pid' => '37',
          'pos_name' => '品牌.配饰',
          'identifier' => 'recommend_brands_accessories',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653873',
          'updated' => '1386654048',
          'city' => 'sh',
        ),
        'recommend_brands_maternal_child' => 
        array (
          'pos_id' => '47',
          'pos_pid' => '37',
          'pos_name' => '品牌.母婴',
          'identifier' => 'recommend_brands_maternal_child',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386653926',
          'updated' => '1386654058',
          'city' => 'sh',
        ),
        'recommend_brands_bedding' => 
        array (
          'pos_id' => '48',
          'pos_pid' => '37',
          'pos_name' => '品牌.床品',
          'identifier' => 'recommend_brands_bedding',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1386654130',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'good_show' => 
    array (
      'pos_id' => '49',
      'pos_pid' => '0',
      'pos_name' => '商品详情页',
      'identifier' => 'good_show',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1387422830',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'good_show_hot' => 
        array (
          'pos_id' => '50',
          'pos_pid' => '49',
          'pos_name' => '热门商品',
          'identifier' => 'good_show_hot',
          'pos_url' => '',
          'width' => '160',
          'height' => '210',
          'sequence' => '99',
          'created' => '1387422864',
          'updated' => '1387422998',
          'city' => 'sh',
        ),
        'good_show_guess' => 
        array (
          'pos_id' => '51',
          'pos_pid' => '49',
          'pos_name' => '猜你喜欢',
          'identifier' => 'good_show_guess',
          'pos_url' => '',
          'width' => '160',
          'height' => '210',
          'sequence' => '99',
          'created' => '1387423042',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'shop_recommend' => 
    array (
      'pos_id' => '52',
      'pos_pid' => '0',
      'pos_name' => '旗舰店推荐',
      'identifier' => 'shop_recommend',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1403673221',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'shop_background' => 
        array (
          'pos_id' => '54',
          'pos_pid' => '52',
          'pos_name' => '店招背景图片',
          'identifier' => 'shop_background',
          'pos_url' => '',
          'width' => '1200',
          'height' => '120',
          'sequence' => '1',
          'created' => '1403673571',
          'updated' => '1404191489',
          'city' => 'sh',
        ),
        'shop_figure' => 
        array (
          'pos_id' => '55',
          'pos_pid' => '52',
          'pos_name' => '店铺大图',
          'identifier' => 'shop_figure',
          'pos_url' => '',
          'width' => '1200',
          'height' => '300',
          'sequence' => '2',
          'created' => '1403673705',
          'updated' => '0',
          'city' => 'sh',
        ),
        'shop_good' => 
        array (
          'pos_id' => '58',
          'pos_pid' => '52',
          'pos_name' => '推荐商品',
          'identifier' => 'shop_good',
          'pos_url' => '',
          'width' => '296',
          'height' => '296',
          'sequence' => '3',
          'created' => '1403674047',
          'updated' => '1404183870',
          'city' => 'sh',
        ),
        'shop_bar' => 
        array (
          'pos_id' => '57',
          'pos_pid' => '52',
          'pos_name' => '标题栏图片',
          'identifier' => 'shop_bar',
          'pos_url' => '',
          'width' => '1200',
          'height' => '120',
          'sequence' => '4',
          'created' => '1403673985',
          'updated' => '0',
          'city' => 'sh',
        ),
        'shop_active' => 
        array (
          'pos_id' => '70',
          'pos_pid' => '52',
          'pos_name' => '活动小图',
          'identifier' => 'shop_active',
          'pos_url' => '',
          'width' => '296',
          'height' => '296',
          'sequence' => '5',
          'created' => '1409278790',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_recommend' => 
        array (
          'pos_id' => '53',
          'pos_pid' => '52',
          'pos_name' => 'APP活动推荐',
          'identifier' => 'app_recommend',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '6',
          'created' => '1403673357',
          'updated' => '1404191395',
          'city' => 'sh',
        ),
      ),
    ),
    'brand_recommended' => 
    array (
      'pos_id' => '62',
      'pos_pid' => '0',
      'pos_name' => '品牌推荐',
      'identifier' => 'brand_recommended',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1403770246',
      'updated' => '1403772537',
      'city' => 'sh',
      'child' => 
      array (
        'brand_logo' => 
        array (
          'pos_id' => '63',
          'pos_pid' => '62',
          'pos_name' => '品牌LOGO',
          'identifier' => 'brand_logo',
          'pos_url' => '',
          'width' => '200',
          'height' => '80',
          'sequence' => '99',
          'created' => '1403770386',
          'updated' => '1404186132',
          'city' => 'sh',
        ),
        'brand_figure' => 
        array (
          'pos_id' => '64',
          'pos_pid' => '62',
          'pos_name' => '品牌形象图',
          'identifier' => 'brand_figure',
          'pos_url' => '',
          'width' => '950',
          'height' => '300',
          'sequence' => '99',
          'created' => '1403770406',
          'updated' => '1404191292',
          'city' => 'sh',
        ),
        'brand_head' => 
        array (
          'pos_id' => '65',
          'pos_pid' => '62',
          'pos_name' => '品牌头图（APP）',
          'identifier' => 'brand_head',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1409107836',
          'updated' => '0',
          'city' => 'sh',
        ),
        'brand_icon' => 
        array (
          'pos_id' => '66',
          'pos_pid' => '62',
          'pos_name' => '品牌标识（APP）',
          'identifier' => 'brand_icon',
          'pos_url' => '',
          'width' => '125',
          'height' => '125',
          'sequence' => '99',
          'created' => '1409107897',
          'updated' => '1418633874',
          'city' => 'sh',
        ),
        'brand_recom_small' => 
        array (
          'pos_id' => '77',
          'pos_pid' => '62',
          'pos_name' => '品牌推荐小图(APP)',
          'identifier' => 'brand_recom_small',
          'pos_url' => '',
          'width' => '294',
          'height' => '200',
          'sequence' => '99',
          'created' => '1411624925',
          'updated' => '1418629700',
          'city' => 'sh',
        ),
        'brand_recom_big' => 
        array (
          'pos_id' => '78',
          'pos_pid' => '62',
          'pos_name' => '品牌推荐大图(APP)',
          'identifier' => 'brand_recom_big',
          'pos_url' => '',
          'width' => '294',
          'height' => '412',
          'sequence' => '99',
          'created' => '1411624937',
          'updated' => '1441094193',
          'city' => 'sh',
        ),
      ),
    ),
    'market' => 
    array (
      'pos_id' => '67',
      'pos_pid' => '0',
      'pos_name' => '商场推荐',
      'identifier' => 'market',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1409109431',
      'updated' => '1418629779',
      'city' => 'sh',
      'child' => 
      array (
        'market_logo' => 
        array (
          'pos_id' => '68',
          'pos_pid' => '67',
          'pos_name' => '商场LOGO',
          'identifier' => 'market_logo',
          'pos_url' => '',
          'width' => '120',
          'height' => '120',
          'sequence' => '99',
          'created' => '1409109494',
          'updated' => '0',
          'city' => 'sh',
        ),
        'market_head' => 
        array (
          'pos_id' => '69',
          'pos_pid' => '67',
          'pos_name' => '商场头图',
          'identifier' => 'market_head',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1409109525',
          'updated' => '0',
          'city' => 'sh',
        ),
        'market_recom' => 
        array (
          'pos_id' => '79',
          'pos_pid' => '67',
          'pos_name' => '商场推荐图 (APP)',
          'identifier' => 'market_recom',
          'pos_url' => '',
          'width' => '186',
          'height' => '196',
          'sequence' => '99',
          'created' => '1411636868',
          'updated' => '1418629739',
          'city' => 'sh',
        ),
        'market_banner' => 
        array (
          'pos_id' => '246',
          'pos_pid' => '67',
          'pos_name' => '商场通栏',
          'identifier' => 'market_banner',
          'pos_url' => '',
          'width' => '640',
          'height' => '70',
          'sequence' => '99',
          'created' => '1430794792',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'shop' => 
    array (
      'pos_id' => '72',
      'pos_pid' => '0',
      'pos_name' => '店铺管理',
      'identifier' => 'shop',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1410418791',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'shop_head_img' => 
        array (
          'pos_id' => '73',
          'pos_pid' => '72',
          'pos_name' => '店铺头图',
          'identifier' => 'shop_head_img',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1410418839',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'buygood' => 
    array (
      'pos_id' => '135',
      'pos_pid' => '0',
      'pos_name' => '团购商品',
      'identifier' => 'buygood',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1417687182',
      'updated' => '1418267519',
      'city' => 'sh',
      'child' => 
      array (
        'buygood_img_large' => 
        array (
          'pos_id' => '136',
          'pos_pid' => '135',
          'pos_name' => '商品大图',
          'identifier' => 'buygood_img_large',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1417687235',
          'updated' => '0',
          'city' => 'sh',
        ),
        'buygood_img_small' => 
        array (
          'pos_id' => '137',
          'pos_pid' => '135',
          'pos_name' => '商品小图',
          'identifier' => 'buygood_img_small',
          'pos_url' => '',
          'width' => '240',
          'height' => '240',
          'sequence' => '99',
          'created' => '1417687283',
          'updated' => '1418269163',
          'city' => 'sh',
        ),
        'buygood_banner' => 
        array (
          'pos_id' => '138',
          'pos_pid' => '135',
          'pos_name' => '团购轮播图',
          'identifier' => 'buygood_banner',
          'pos_url' => '',
          'width' => '1200',
          'height' => '300',
          'sequence' => '99',
          'created' => '1418266361',
          'updated' => '0',
          'city' => 'sh',
        ),
        'buygood_app_banner' => 
        array (
          'pos_id' => '139',
          'pos_pid' => '135',
          'pos_name' => 'APP轮播图',
          'identifier' => 'buygood_app_banner',
          'pos_url' => '',
          'width' => '640',
          'height' => '190',
          'sequence' => '99',
          'created' => '1418266489',
          'updated' => '0',
          'city' => 'sh',
        ),
        'buygood_spike' => 
        array (
          'pos_id' => '140',
          'pos_pid' => '135',
          'pos_name' => '团购秒杀',
          'identifier' => 'buygood_spike',
          'pos_url' => '',
          'width' => '600',
          'height' => '280',
          'sequence' => '99',
          'created' => '1418266559',
          'updated' => '0',
          'city' => 'sh',
        ),
        'buygood_hot' => 
        array (
          'pos_id' => '141',
          'pos_pid' => '135',
          'pos_name' => '热门推荐',
          'identifier' => 'buygood_hot',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1418267554',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'app_home_version_four' => 
    array (
      'pos_id' => '142',
      'pos_pid' => '0',
      'pos_name' => 'APP首页新版4.0',
      'identifier' => 'app_home_version_four',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1426665879',
      'updated' => '1426665968',
      'city' => 'sh',
      'child' => 
      array (
        'app_home_large_icons' => 
        array (
          'pos_id' => '152',
          'pos_pid' => '142',
          'pos_name' => '大图标',
          'identifier' => 'app_home_large_icons',
          'pos_url' => '',
          'width' => '142',
          'height' => '142',
          'sequence' => '99',
          'created' => '1426680709',
          'updated' => '1426681148',
          'city' => 'sh',
        ),
        'app_home_small_icons' => 
        array (
          'pos_id' => '153',
          'pos_pid' => '142',
          'pos_name' => '小图标',
          'identifier' => 'app_home_small_icons',
          'pos_url' => '',
          'width' => '91',
          'height' => '91',
          'sequence' => '99',
          'created' => '1426681186',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_home_limited_spike' => 
        array (
          'pos_id' => '154',
          'pos_pid' => '142',
          'pos_name' => '限量秒杀',
          'identifier' => 'app_home_limited_spike',
          'pos_url' => '',
          'width' => '320',
          'height' => '350',
          'sequence' => '99',
          'created' => '1426681292',
          'updated' => '1426729731',
          'city' => 'sh',
        ),
        'app_home_daily_deals' => 
        array (
          'pos_id' => '155',
          'pos_pid' => '142',
          'pos_name' => '每日特卖',
          'identifier' => 'app_home_daily_deals',
          'pos_url' => '',
          'width' => '320',
          'height' => '150',
          'sequence' => '99',
          'created' => '1426681347',
          'updated' => '1426729752',
          'city' => 'sh',
        ),
        'app_home_buying_vouchers' => 
        array (
          'pos_id' => '156',
          'pos_pid' => '142',
          'pos_name' => '抢购代金券',
          'identifier' => 'app_home_buying_vouchers',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1426681414',
          'updated' => '1426730442',
          'city' => 'sh',
        ),
        'app_home_big_drive_to' => 
        array (
          'pos_id' => '157',
          'pos_pid' => '142',
          'pos_name' => '大牌驾到',
          'identifier' => 'app_home_big_drive_to',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1426681471',
          'updated' => '1426730451',
          'city' => 'sh',
        ),
        'app_home_recommended_coupons' => 
        array (
          'pos_id' => '158',
          'pos_pid' => '142',
          'pos_name' => '推荐券',
          'identifier' => 'app_home_recommended_coupons',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1426681548',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_home_recommended_for_you' => 
        array (
          'pos_id' => '159',
          'pos_pid' => '142',
          'pos_name' => '为您推荐',
          'identifier' => 'app_home_recommended_for_you',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1426681596',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'app_brand_version_four' => 
    array (
      'pos_id' => '235',
      'pos_pid' => '0',
      'pos_name' => '品牌4.0',
      'identifier' => 'app_brand_version_four',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1430709433',
      'updated' => '1430710330',
      'city' => 'sh',
      'child' => 
      array (
        'app_brand_banner' => 
        array (
          'pos_id' => '236',
          'pos_pid' => '235',
          'pos_name' => '品牌头部通栏',
          'identifier' => 'app_brand_banner',
          'pos_url' => '',
          'width' => '640',
          'height' => '70',
          'sequence' => '99',
          'created' => '1430710379',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_small' => 
        array (
          'pos_id' => '237',
          'pos_pid' => '235',
          'pos_name' => '品牌小图',
          'identifier' => 'app_brand_small',
          'pos_url' => '',
          'width' => '300',
          'height' => '200',
          'sequence' => '99',
          'created' => '1430710470',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_big' => 
        array (
          'pos_id' => '238',
          'pos_pid' => '235',
          'pos_name' => '品牌大图',
          'identifier' => 'app_brand_big',
          'pos_url' => '',
          'width' => '300',
          'height' => '410',
          'sequence' => '99',
          'created' => '1430710500',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_ticket' => 
        array (
          'pos_id' => '239',
          'pos_pid' => '235',
          'pos_name' => '品牌推荐券',
          'identifier' => 'app_brand_ticket',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430710547',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_band_recommend' => 
        array (
          'pos_id' => '245',
          'pos_pid' => '235',
          'pos_name' => '推荐品牌',
          'identifier' => 'app_band_recommend',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430731661',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'app_brand_sort' => 
    array (
      'pos_id' => '240',
      'pos_pid' => '0',
      'pos_name' => '品牌分类',
      'identifier' => 'app_brand_sort',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1430717911',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'app_band_billboard' => 
        array (
          'pos_id' => '241',
          'pos_pid' => '240',
          'pos_name' => '流行榜',
          'identifier' => 'app_band_billboard',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430718001',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_fanart' => 
        array (
          'pos_id' => '242',
          'pos_pid' => '240',
          'pos_name' => '文艺范',
          'identifier' => 'app_brand_fanart',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430718049',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_luxury' => 
        array (
          'pos_id' => '243',
          'pos_pid' => '240',
          'pos_name' => '奢侈品',
          'identifier' => 'app_brand_luxury',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430718121',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_brand_fashion' => 
        array (
          'pos_id' => '244',
          'pos_pid' => '240',
          'pos_name' => '快时尚',
          'identifier' => 'app_brand_fashion',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1430718157',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'commodity' => 
    array (
      'pos_id' => '247',
      'pos_pid' => '0',
      'pos_name' => '商城商品',
      'identifier' => 'commodity',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1436408053',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'commodity_banner_large' => 
        array (
          'pos_id' => '248',
          'pos_pid' => '247',
          'pos_name' => '广告大图',
          'identifier' => 'commodity_banner_large',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1436408206',
          'updated' => '0',
          'city' => 'sh',
        ),
        'commodity_banner_small' => 
        array (
          'pos_id' => '249',
          'pos_pid' => '247',
          'pos_name' => '广告小图',
          'identifier' => 'commodity_banner_small',
          'pos_url' => '',
          'width' => '315',
          'height' => '140',
          'sequence' => '99',
          'created' => '1436408240',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'discount' => 
    array (
      'pos_id' => '250',
      'pos_pid' => '0',
      'pos_name' => '折扣管理',
      'identifier' => 'discount',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1439894530',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'discount_banner' => 
        array (
          'pos_id' => '251',
          'pos_pid' => '250',
          'pos_name' => '推荐广告',
          'identifier' => 'discount_banner',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1439894685',
          'updated' => '1440037196',
          'city' => 'sh',
        ),
        'discount_brand_recommend' => 
        array (
          'pos_id' => '252',
          'pos_pid' => '250',
          'pos_name' => '热门品牌推荐',
          'identifier' => 'discount_brand_recommend',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1439965476',
          'updated' => '1439966120',
          'city' => 'sh',
        ),
        'discount_market_recommend' => 
        array (
          'pos_id' => '253',
          'pos_pid' => '250',
          'pos_name' => '热门商场推荐',
          'identifier' => 'discount_market_recommend',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1439976794',
          'updated' => '1441095399',
          'city' => 'sh',
        ),
        'discount_recommend' => 
        array (
          'pos_id' => '254',
          'pos_pid' => '250',
          'pos_name' => '折扣推荐',
          'identifier' => 'discount_recommend',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1440037229',
          'updated' => '0',
          'city' => 'sh',
        ),
        'discount_circle_recommend' => 
        array (
          'pos_id' => '255',
          'pos_pid' => '250',
          'pos_name' => '热门商圈推荐',
          'identifier' => 'discount_circle_recommend',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1440489878',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'app_home_version_six' => 
    array (
      'pos_id' => '256',
      'pos_pid' => '0',
      'pos_name' => 'APP首页新版6.0',
      'identifier' => 'app_home_version_six',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1445224037',
      'updated' => '1445225952',
      'city' => 'sh',
      'child' => 
      array (
        'app_home_six_banner' => 
        array (
          'pos_id' => '257',
          'pos_pid' => '256',
          'pos_name' => '推荐广告five',
          'identifier' => 'app_home_six_banner',
          'pos_url' => '',
          'width' => '750',
          'height' => '300',
          'sequence' => '1',
          'created' => '1445224126',
          'updated' => '1445225358',
          'city' => 'sh',
        ),
        'app_home_six_icon' => 
        array (
          'pos_id' => '258',
          'pos_pid' => '256',
          'pos_name' => '大图标five',
          'identifier' => 'app_home_six_icon',
          'pos_url' => '',
          'width' => '100',
          'height' => '100',
          'sequence' => '2',
          'created' => '1445224176',
          'updated' => '1445334787',
          'city' => 'sh',
        ),
        'app_home_six_oneyuanpurchase' => 
        array (
          'pos_id' => '265',
          'pos_pid' => '256',
          'pos_name' => '一元众筹',
          'identifier' => 'app_home_six_oneyuanpurchase',
          'pos_url' => '',
          'width' => '375',
          'height' => '280',
          'sequence' => '3',
          'created' => '1445933355',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_home_six_comeandgrap' => 
        array (
          'pos_id' => '266',
          'pos_pid' => '256',
          'pos_name' => '快来抢',
          'identifier' => 'app_home_six_comeandgrap',
          'pos_url' => '',
          'width' => '365',
          'height' => '140',
          'sequence' => '4',
          'created' => '1445933456',
          'updated' => '1445933472',
          'city' => 'sh',
        ),
        'app_home_six_auction' => 
        array (
          'pos_id' => '267',
          'pos_pid' => '256',
          'pos_name' => '拍卖会',
          'identifier' => 'app_home_six_auction',
          'pos_url' => '',
          'width' => '365',
          'height' => '140',
          'sequence' => '5',
          'created' => '1445933525',
          'updated' => '0',
          'city' => 'sh',
        ),
        'app_home_six_daren' => 
        array (
          'pos_id' => '260',
          'pos_pid' => '256',
          'pos_name' => '达人说',
          'identifier' => 'app_home_six_daren',
          'pos_url' => '',
          'width' => '700',
          'height' => '328',
          'sequence' => '6',
          'created' => '1445224506',
          'updated' => '1445389976',
          'city' => 'sh',
        ),
        'app_home_six_love' => 
        array (
          'pos_id' => '261',
          'pos_pid' => '256',
          'pos_name' => '猜你喜欢five',
          'identifier' => 'app_home_six_love',
          'pos_url' => '',
          'width' => '700',
          'height' => '328',
          'sequence' => '7',
          'created' => '1445224622',
          'updated' => '1445389989',
          'city' => 'sh',
        ),
      ),
    ),
    'banner' => 
    array (
      'pos_id' => '262',
      'pos_pid' => '0',
      'pos_name' => '外部广告',
      'identifier' => 'banner',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1445336235',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'banner_external' => 
        array (
          'pos_id' => '263',
          'pos_pid' => '262',
          'pos_name' => '广告管理',
          'identifier' => 'banner_external',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1445336347',
          'updated' => '0',
          'city' => 'sh',
        ),
      ),
    ),
    'activity' => 
    array (
      'pos_id' => '268',
      'pos_pid' => '0',
      'pos_name' => '活动广告',
      'identifier' => 'activity',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1446000593',
      'updated' => '1446109418',
      'city' => 'sh',
      'child' => 
      array (
        'activity_oneyuanpurchase_banner' => 
        array (
          'pos_id' => '269',
          'pos_pid' => '268',
          'pos_name' => '一元众筹广告推荐',
          'identifier' => 'activity_oneyuanpurchase_banner',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1446000661',
          'updated' => '1446109460',
          'city' => 'sh',
        ),
      ),
    ),
    'tianshan' => 
    array (
      'pos_id' => '270',
      'pos_pid' => '0',
      'pos_name' => '天山店',
      'identifier' => 'tianshan',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1454390959',
      'updated' => '0',
      'city' => 'sh',
      'child' => 
      array (
        'tianshan_banner' => 
        array (
          'pos_id' => '271',
          'pos_pid' => '270',
          'pos_name' => '天山店广告推荐',
          'identifier' => 'tianshan_banner',
          'pos_url' => '',
          'width' => '750',
          'height' => '300',
          'sequence' => '99',
          'created' => '1454391048',
          'updated' => '1454391113',
          'city' => 'sh',
        ),
        'tianshan_icon' => 
        array (
          'pos_id' => '272',
          'pos_pid' => '270',
          'pos_name' => '天山店图标',
          'identifier' => 'tianshan_icon',
          'pos_url' => '',
          'width' => '150',
          'height' => '150',
          'sequence' => '99',
          'created' => '1454391186',
          'updated' => '1454391522',
          'city' => 'sh',
        ),
        'tianshan_shop' => 
        array (
          'pos_id' => '273',
          'pos_pid' => '270',
          'pos_name' => '天山店品牌店铺推荐',
          'identifier' => 'tianshan_shop',
          'pos_url' => '',
          'width' => '700',
          'height' => '328',
          'sequence' => '99',
          'created' => '1454391228',
          'updated' => '1454391482',
          'city' => 'sh',
        ),
      ),
    ),
  ),
  'nj' => 
  array (
    'index' => 
    array (
      'pos_id' => '81',
      'pos_pid' => '0',
      'pos_name' => '首页',
      'identifier' => 'index',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414554783',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'index_latest_event' => 
        array (
          'pos_id' => '82',
          'pos_pid' => '81',
          'pos_name' => '最新活动',
          'identifier' => 'index_latest_event',
          'pos_url' => '',
          'width' => '220',
          'height' => '125',
          'sequence' => '99',
          'created' => '1414554825',
          'updated' => '0',
          'city' => 'nj',
        ),
        'index_img_large' => 
        array (
          'pos_id' => '83',
          'pos_pid' => '81',
          'pos_name' => '轮播大图',
          'identifier' => 'index_img_large',
          'pos_url' => '',
          'width' => '1200',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414559053',
          'updated' => '0',
          'city' => 'nj',
        ),
        'index_top_shop' => 
        array (
          'pos_id' => '84',
          'pos_pid' => '81',
          'pos_name' => '热门店铺',
          'identifier' => 'index_top_shop',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1414559088',
          'updated' => '0',
          'city' => 'nj',
        ),
        'index_value_pick' => 
        array (
          'pos_id' => '85',
          'pos_pid' => '81',
          'pos_name' => '超值精选',
          'identifier' => 'index_value_pick',
          'pos_url' => '',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414559125',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'iphone' => 
    array (
      'pos_id' => '86',
      'pos_pid' => '0',
      'pos_name' => '手机端',
      'identifier' => 'iphone',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414559153',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'phone_head' => 
        array (
          'pos_id' => '87',
          'pos_pid' => '86',
          'pos_name' => '头部推荐',
          'identifier' => 'phone_head',
          'pos_url' => '',
          'width' => '640',
          'height' => '190',
          'sequence' => '99',
          'created' => '1414559265',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'nav' => 
    array (
      'pos_id' => '88',
      'pos_pid' => '0',
      'pos_name' => '导航',
      'identifier' => 'nav',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414559280',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'nav_good_sort' => 
        array (
          'pos_id' => '89',
          'pos_pid' => '88',
          'pos_name' => '按分类',
          'identifier' => 'nav_good_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1414559312',
          'updated' => '0',
          'city' => 'nj',
        ),
        'nav_brand_sort' => 
        array (
          'pos_id' => '90',
          'pos_pid' => '88',
          'pos_name' => '按品牌',
          'identifier' => 'nav_brand_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1414559331',
          'updated' => '0',
          'city' => 'nj',
        ),
        'nav_region_sort' => 
        array (
          'pos_id' => '91',
          'pos_pid' => '88',
          'pos_name' => '按区域',
          'identifier' => 'nav_region_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1414559364',
          'updated' => '0',
          'city' => 'nj',
        ),
        'nav_circle_sort' => 
        array (
          'pos_id' => '92',
          'pos_pid' => '88',
          'pos_name' => '按商圈',
          'identifier' => 'nav_circle_sort',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1414559387',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'recommend_goods' => 
    array (
      'pos_id' => '93',
      'pos_pid' => '0',
      'pos_name' => '分类商品推荐',
      'identifier' => 'recommend_goods',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414572515',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'recommend_goods_wome' => 
        array (
          'pos_id' => '94',
          'pos_pid' => '93',
          'pos_name' => '女装',
          'identifier' => 'recommend_goods_wome',
          'pos_url' => 'http://buy.mplife.com/home/good/list/sid/22_0_0_0_0/order/1',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414572558',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_goods_shoe' => 
        array (
          'pos_id' => '95',
          'pos_pid' => '93',
          'pos_name' => '鞋包.配饰',
          'identifier' => 'recommend_goods_shoe',
          'pos_url' => 'http://buy.mplife.com/home/good/list/sid/19_0_0_0_0/order/1',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414572939',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_goods_beautif' => 
        array (
          'pos_id' => '96',
          'pos_pid' => '93',
          'pos_name' => '美颜.家居',
          'identifier' => 'recommend_goods_beautif',
          'pos_url' => 'http://buy.mplife.com/home/good/list/sid/27_0_0_0_0/order/1',
          'width' => '220',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414573035',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'recommend_brands' => 
    array (
      'pos_id' => '97',
      'pos_pid' => '0',
      'pos_name' => '分类品牌推荐',
      'identifier' => 'recommend_brands',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414633388',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'recommend_brands_wom' => 
        array (
          'pos_id' => '98',
          'pos_pid' => '97',
          'pos_name' => '品牌.女装',
          'identifier' => 'recommend_brands_wom',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633444',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_shoes' => 
        array (
          'pos_id' => '99',
          'pos_pid' => '97',
          'pos_name' => '品牌.鞋包',
          'identifier' => 'recommend_brands_shoes',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633480',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_underwear' => 
        array (
          'pos_id' => '100',
          'pos_pid' => '97',
          'pos_name' => '品牌.内衣',
          'identifier' => 'recommend_brands_underwear',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633502',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_men' => 
        array (
          'pos_id' => '101',
          'pos_pid' => '97',
          'pos_name' => '品牌.男装',
          'identifier' => 'recommend_brands_men',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633523',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_accessories' => 
        array (
          'pos_id' => '102',
          'pos_pid' => '97',
          'pos_name' => '品牌.配饰',
          'identifier' => 'recommend_brands_accessories',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633551',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_maternal_child' => 
        array (
          'pos_id' => '103',
          'pos_pid' => '97',
          'pos_name' => '品牌.母婴',
          'identifier' => 'recommend_brands_maternal_child',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633575',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_bedding' => 
        array (
          'pos_id' => '104',
          'pos_pid' => '97',
          'pos_name' => '品牌.生活',
          'identifier' => 'recommend_brands_bedding',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633602',
          'updated' => '0',
          'city' => 'nj',
        ),
        'recommend_brands_home' => 
        array (
          'pos_id' => '105',
          'pos_pid' => '97',
          'pos_name' => '品牌.家居',
          'identifier' => 'recommend_brands_home',
          'pos_url' => '',
          'width' => '100',
          'height' => '50',
          'sequence' => '99',
          'created' => '1414633626',
          'updated' => '1415771594',
          'city' => 'nj',
        ),
      ),
    ),
    'good_show' => 
    array (
      'pos_id' => '106',
      'pos_pid' => '0',
      'pos_name' => '商品详情页',
      'identifier' => 'good_show',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414660333',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'good_show_hot' => 
        array (
          'pos_id' => '107',
          'pos_pid' => '106',
          'pos_name' => '热门商品',
          'identifier' => 'good_show_hot',
          'pos_url' => '',
          'width' => '160',
          'height' => '210',
          'sequence' => '99',
          'created' => '1414660391',
          'updated' => '0',
          'city' => 'nj',
        ),
        'good_show_guess' => 
        array (
          'pos_id' => '108',
          'pos_pid' => '106',
          'pos_name' => '猜你喜欢',
          'identifier' => 'good_show_guess',
          'pos_url' => '',
          'width' => '160',
          'height' => '210',
          'sequence' => '99',
          'created' => '1414660419',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'shop_recommend' => 
    array (
      'pos_id' => '109',
      'pos_pid' => '0',
      'pos_name' => '旗舰店推荐',
      'identifier' => 'shop_recommend',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414660470',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'shop_background' => 
        array (
          'pos_id' => '110',
          'pos_pid' => '109',
          'pos_name' => '店招背景图片',
          'identifier' => 'shop_background',
          'pos_url' => '',
          'width' => '1200',
          'height' => '120',
          'sequence' => '99',
          'created' => '1414660510',
          'updated' => '0',
          'city' => 'nj',
        ),
        'shop_figure' => 
        array (
          'pos_id' => '111',
          'pos_pid' => '109',
          'pos_name' => '店铺大图',
          'identifier' => 'shop_figure',
          'pos_url' => '',
          'width' => '1200',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414660533',
          'updated' => '0',
          'city' => 'nj',
        ),
        'shop_good' => 
        array (
          'pos_id' => '112',
          'pos_pid' => '109',
          'pos_name' => '推荐商品',
          'identifier' => 'shop_good',
          'pos_url' => '',
          'width' => '296',
          'height' => '296',
          'sequence' => '99',
          'created' => '1414660564',
          'updated' => '0',
          'city' => 'nj',
        ),
        'shop_bar' => 
        array (
          'pos_id' => '113',
          'pos_pid' => '109',
          'pos_name' => '标题栏图片',
          'identifier' => 'shop_bar',
          'pos_url' => '',
          'width' => '1200',
          'height' => '30',
          'sequence' => '99',
          'created' => '1414660595',
          'updated' => '0',
          'city' => 'nj',
        ),
        'shop_active' => 
        array (
          'pos_id' => '114',
          'pos_pid' => '109',
          'pos_name' => '活动小图',
          'identifier' => 'shop_active',
          'pos_url' => '',
          'width' => '296',
          'height' => '296',
          'sequence' => '99',
          'created' => '1414660626',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_recommend' => 
        array (
          'pos_id' => '115',
          'pos_pid' => '109',
          'pos_name' => 'APP活动推荐',
          'identifier' => 'app_recommend',
          'pos_url' => '',
          'width' => '640',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414660651',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_figure' => 
        array (
          'pos_id' => '116',
          'pos_pid' => '109',
          'pos_name' => 'APP店铺形象图',
          'identifier' => 'app_figure',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1414660679',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'brand_recommended' => 
    array (
      'pos_id' => '117',
      'pos_pid' => '0',
      'pos_name' => '品牌推荐',
      'identifier' => 'brand_recommended',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414660722',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'brand_logo' => 
        array (
          'pos_id' => '118',
          'pos_pid' => '117',
          'pos_name' => '品牌LOGO',
          'identifier' => 'brand_logo',
          'pos_url' => '',
          'width' => '200',
          'height' => '80',
          'sequence' => '99',
          'created' => '1414660760',
          'updated' => '0',
          'city' => 'nj',
        ),
        'brand_figure' => 
        array (
          'pos_id' => '119',
          'pos_pid' => '117',
          'pos_name' => '品牌形象图',
          'identifier' => 'brand_figure',
          'pos_url' => '',
          'width' => '950',
          'height' => '300',
          'sequence' => '99',
          'created' => '1414660790',
          'updated' => '0',
          'city' => 'nj',
        ),
        'brand_head' => 
        array (
          'pos_id' => '120',
          'pos_pid' => '117',
          'pos_name' => '品牌头图（APP）',
          'identifier' => 'brand_head',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1414660822',
          'updated' => '0',
          'city' => 'nj',
        ),
        'brand_icon' => 
        array (
          'pos_id' => '121',
          'pos_pid' => '117',
          'pos_name' => '品牌标识（APP）',
          'identifier' => 'brand_icon',
          'pos_url' => '',
          'width' => '125',
          'height' => '125',
          'sequence' => '99',
          'created' => '1414660846',
          'updated' => '0',
          'city' => 'nj',
        ),
        'brand_recom_big' => 
        array (
          'pos_id' => '128',
          'pos_pid' => '117',
          'pos_name' => '品牌推荐大图(APP)',
          'identifier' => 'brand_recom_big',
          'pos_url' => '',
          'width' => '294',
          'height' => '412',
          'sequence' => '99',
          'created' => '1416467663',
          'updated' => '1418631892',
          'city' => 'nj',
        ),
        'brand_recom_small' => 
        array (
          'pos_id' => '129',
          'pos_pid' => '117',
          'pos_name' => '品牌推荐小图(APP)',
          'identifier' => 'brand_recom_small',
          'pos_url' => '',
          'width' => '294',
          'height' => '200',
          'sequence' => '99',
          'created' => '1416467694',
          'updated' => '1418631902',
          'city' => 'nj',
        ),
      ),
    ),
    'market' => 
    array (
      'pos_id' => '122',
      'pos_pid' => '0',
      'pos_name' => '商场模块',
      'identifier' => 'market',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414660879',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'market_logo' => 
        array (
          'pos_id' => '123',
          'pos_pid' => '122',
          'pos_name' => '商场LOGO',
          'identifier' => 'market_logo',
          'pos_url' => '',
          'width' => '125',
          'height' => '125',
          'sequence' => '99',
          'created' => '1414660912',
          'updated' => '0',
          'city' => 'nj',
        ),
        'market_head' => 
        array (
          'pos_id' => '124',
          'pos_pid' => '122',
          'pos_name' => '商场头图',
          'identifier' => 'market_head',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1414660940',
          'updated' => '0',
          'city' => 'nj',
        ),
        'market_recom' => 
        array (
          'pos_id' => '130',
          'pos_pid' => '122',
          'pos_name' => '商场推荐图 (APP)',
          'identifier' => 'market_recom',
          'pos_url' => '',
          'width' => '188',
          'height' => '196',
          'sequence' => '99',
          'created' => '1416467724',
          'updated' => '1418631911',
          'city' => 'nj',
        ),
      ),
    ),
    'shop' => 
    array (
      'pos_id' => '125',
      'pos_pid' => '0',
      'pos_name' => '店铺管理',
      'identifier' => 'shop',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1414660962',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'shop_head_img' => 
        array (
          'pos_id' => '126',
          'pos_pid' => '125',
          'pos_name' => '店铺头图',
          'identifier' => 'shop_head_img',
          'pos_url' => '',
          'width' => '640',
          'height' => '400',
          'sequence' => '99',
          'created' => '1414660987',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
    'app_home_version_four' => 
    array (
      'pos_id' => '217',
      'pos_pid' => '0',
      'pos_name' => 'APP首页新版4.0',
      'identifier' => 'app_home_version_four',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1427245764',
      'updated' => '0',
      'city' => 'nj',
      'child' => 
      array (
        'app_home_large_icons' => 
        array (
          'pos_id' => '218',
          'pos_pid' => '217',
          'pos_name' => '大图标',
          'identifier' => 'app_home_large_icons',
          'pos_url' => '',
          'width' => '142',
          'height' => '142',
          'sequence' => '99',
          'created' => '1427245788',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_small_icons' => 
        array (
          'pos_id' => '219',
          'pos_pid' => '217',
          'pos_name' => '小图标',
          'identifier' => 'app_home_small_icons',
          'pos_url' => '',
          'width' => '91',
          'height' => '91',
          'sequence' => '99',
          'created' => '1427245807',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_limited_spike' => 
        array (
          'pos_id' => '220',
          'pos_pid' => '217',
          'pos_name' => '限量秒杀',
          'identifier' => 'app_home_limited_spike',
          'pos_url' => '',
          'width' => '320',
          'height' => '350',
          'sequence' => '99',
          'created' => '1427245835',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_daily_deals' => 
        array (
          'pos_id' => '221',
          'pos_pid' => '217',
          'pos_name' => '每日特卖',
          'identifier' => 'app_home_daily_deals',
          'pos_url' => '',
          'width' => '320',
          'height' => '150',
          'sequence' => '99',
          'created' => '1427245852',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_buying_vouchers' => 
        array (
          'pos_id' => '222',
          'pos_pid' => '217',
          'pos_name' => '抢购代金券',
          'identifier' => 'app_home_buying_vouchers',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1427245872',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_big_drive_to' => 
        array (
          'pos_id' => '223',
          'pos_pid' => '217',
          'pos_name' => '大牌驾到',
          'identifier' => 'app_home_big_drive_to',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1427245890',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_recommended_coupons' => 
        array (
          'pos_id' => '224',
          'pos_pid' => '217',
          'pos_name' => '推荐券',
          'identifier' => 'app_home_recommended_coupons',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1427245902',
          'updated' => '0',
          'city' => 'nj',
        ),
        'app_home_recommended_for_you' => 
        array (
          'pos_id' => '225',
          'pos_pid' => '217',
          'pos_name' => '为您推荐',
          'identifier' => 'app_home_recommended_for_you',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1427245916',
          'updated' => '0',
          'city' => 'nj',
        ),
      ),
    ),
  ),
  'nb' => 
  array (
    'app_home_version_four' => 
    array (
      'pos_id' => '226',
      'pos_pid' => '0',
      'pos_name' => 'APP首页新版4.0',
      'identifier' => 'app_home_version_four',
      'pos_url' => '',
      'width' => '0',
      'height' => '0',
      'sequence' => '99',
      'created' => '1427245939',
      'updated' => '0',
      'city' => 'nb',
      'child' => 
      array (
        'app_home_large_icons' => 
        array (
          'pos_id' => '227',
          'pos_pid' => '226',
          'pos_name' => '大图标',
          'identifier' => 'app_home_large_icons',
          'pos_url' => '',
          'width' => '142',
          'height' => '142',
          'sequence' => '99',
          'created' => '1427245962',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_small_icons' => 
        array (
          'pos_id' => '228',
          'pos_pid' => '226',
          'pos_name' => '小图标',
          'identifier' => 'app_home_small_icons',
          'pos_url' => '',
          'width' => '91',
          'height' => '91',
          'sequence' => '99',
          'created' => '1427245978',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_limited_spike' => 
        array (
          'pos_id' => '229',
          'pos_pid' => '226',
          'pos_name' => '限量秒杀',
          'identifier' => 'app_home_limited_spike',
          'pos_url' => '',
          'width' => '320',
          'height' => '350',
          'sequence' => '99',
          'created' => '1427246002',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_daily_deals' => 
        array (
          'pos_id' => '230',
          'pos_pid' => '226',
          'pos_name' => '每日特卖',
          'identifier' => 'app_home_daily_deals',
          'pos_url' => '',
          'width' => '320',
          'height' => '150',
          'sequence' => '99',
          'created' => '1427246037',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_buying_vouchers' => 
        array (
          'pos_id' => '231',
          'pos_pid' => '226',
          'pos_name' => '抢购代金券',
          'identifier' => 'app_home_buying_vouchers',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1427246053',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_big_drive_to' => 
        array (
          'pos_id' => '232',
          'pos_pid' => '226',
          'pos_name' => '大牌驾到',
          'identifier' => 'app_home_big_drive_to',
          'pos_url' => '',
          'width' => '160',
          'height' => '200',
          'sequence' => '99',
          'created' => '1427246073',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_recommended_coupons' => 
        array (
          'pos_id' => '233',
          'pos_pid' => '226',
          'pos_name' => '推荐券',
          'identifier' => 'app_home_recommended_coupons',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1427246084',
          'updated' => '0',
          'city' => 'nb',
        ),
        'app_home_recommended_for_you' => 
        array (
          'pos_id' => '234',
          'pos_pid' => '226',
          'pos_name' => '为您推荐',
          'identifier' => 'app_home_recommended_for_you',
          'pos_url' => '',
          'width' => '0',
          'height' => '0',
          'sequence' => '99',
          'created' => '1427246095',
          'updated' => '0',
          'city' => 'nb',
        ),
      ),
    ),
  ),
);