<div  data-sid="{{$commodity.0.shop_id}}" data-cid="{{$commodity.0.ticket_id}}" class="commodity imgs-middle num-l mbtm">
	<div class="imgs-stitle">
		<p class="imgs-shopname">{{$commodity.0.ticket_title}}</p>
		<p class="imgs-price">{{$commodity.0.selling_price}}</p>
	</div>
	<a class="imgs-pic" style="background-image: url({{$commodity.0.thumb_img.0.W400.img_url}})" href='{{$_CONF.SITE_URL}}/home/ticket/wap/tid/{{$commodity.0.ticket_id}}/from/ios#json={"type":"commodity","id":"{{$commodity.0.ticket_id}}"}'></a>
	<img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAMAAAA7EzkRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURf///wAAAFXC034AAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAABpElEQVR4Xu3BgQAAAADDoPlTH+AKVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwakLaAAE+pQU0AAAAAElFTkSuQmCC"/>
</div>

<div  data-sid="{{$commodity.1.shop_id}}" data-cid="{{$commodity.1.ticket_id}}" class="commodity imgs-middle num-r  mbtm">
	<div class="imgs-stitle">
		<p class="imgs-shopname">{{$commodity.1.ticket_title}}</p>
		<p class="imgs-price">{{$commodity.1.selling_price}}</p>
	</div>
	<a class="imgs-pic" style="background-image: url({{$commodity.1.thumb_img.0.W400.img_url}})" href='{{$_CONF.SITE_URL}}/home/ticket/wap/tid/{{$commodity.1.ticket_id}}/from/ios#json={"type":"commodity","id":"{{$commodity.1.ticket_id}}"}'></a>
	<img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAMAAAA7EzkRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURf///wAAAFXC034AAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAABpElEQVR4Xu3BgQAAAADDoPlTH+AKVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwakLaAAE+pQU0AAAAAElFTkSuQmCC"/>
</div>

<div  data-sid="{{$commodity.2.shop_id}}" data-cid="{{$commodity.2.ticket_id}}" class="commodity imgs-small num-l">
	<div class="imgs-stitle">
		<p class="imgs-shopname">{{$commodity.2.ticket_title}}</p>
		<p class="imgs-price">{{$commodity.2.selling_price}}</p>
	</div>
	<a class="imgs-pic" style="background-image: url({{$commodity.2.thumb_img.0.W240.img_url}})" href='{{$_CONF.SITE_URL}}/home/ticket/wap/tid/{{$commodity.2.ticket_id}}/from/ios#json={"type":"commodity","id":"{{$commodity.2.ticket_id}}"}'></a>
	<img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAMAAAA7EzkRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURf///wAAAFXC034AAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAABpElEQVR4Xu3BgQAAAADDoPlTH+AKVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwakLaAAE+pQU0AAAAAElFTkSuQmCC"/>
</div>

<div  data-sid="{{$commodity.3.shop_id}}" data-cid="{{$commodity.3.ticket_id}}" class="commodity imgs-small num-l">
	<div class="imgs-stitle">
		<p class="imgs-shopname">{{$commodity.3.ticket_title}}</p>
		<p class="imgs-price">{{$commodity.3.selling_price}}</p>
	</div>
	<a class="imgs-pic" style="background-image: url({{$commodity.3.thumb_img.0.W240.img_url}})" href='{{$_CONF.SITE_URL}}/home/ticket/wap/tid/{{$commodity.3.ticket_id}}/from/ios#json={"type":"commodity","id":"{{$commodity.3.ticket_id}}"}'></a>
	<img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAMAAAA7EzkRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURf///wAAAFXC034AAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAABpElEQVR4Xu3BgQAAAADDoPlTH+AKVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwakLaAAE+pQU0AAAAAElFTkSuQmCC"/>
</div>

<div  data-sid="{{$commodity.4.shop_id}}" data-cid="{{$commodity.4.ticket_id}}" class="commodity imgs-small num-l">
	<div class="imgs-stitle">
		<p class="imgs-shopname">{{$commodity.4.ticket_title}}</p>
		<p class="imgs-price">{{$commodity.4.selling_price}}</p>
	</div>
	<a class="imgs-pic" style="background-image: url({{$commodity.4.thumb_img.0.W240.img_url}})" href='{{$_CONF.SITE_URL}}/home/ticket/wap/tid/{{$commodity.4.ticket_id}}/from/ios#json={"type":"commodity","id":"{{$commodity.4.ticket_id}}"}'></a>
	<img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAMAAAA7EzkRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURf///wAAAFXC034AAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAABpElEQVR4Xu3BgQAAAADDoPlTH+AKVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwakLaAAE+pQU0AAAAAElFTkSuQmCC"/>
</div>