<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'] . '/packages/xiangle_feed/xiangle_feed_types.php';

$GLOBALS['xiangle_feed_CONSTANTS'] = array();

$GLOBALS['xiangle_feed_CONSTANTS']['FeedTypeMappingGroupType'] = array(5=>2, 22=>2, 20=>2, 23=>2, 24=>2, 25=>2, 26=>2, 27=>2, 13=>2, 14=>2, 9=>2, 11=>1, 16=>2, 7=>2, 18=>1, 28=>1, 29=>1);

?>
